// Code generated by ent, DO NOT EDIT.

package ent

import (
	"slacker/internal/data/ent/record"
	"slacker/internal/data/ent/schema"
	"slacker/internal/data/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	recordFields := schema.Record{}.Fields()
	_ = recordFields
	// recordDescBeginTime is the schema descriptor for begin_time field.
	recordDescBeginTime := recordFields[3].Descriptor()
	// record.DefaultBeginTime holds the default value on creation for the begin_time field.
	record.DefaultBeginTime = recordDescBeginTime.Default.(func() time.Time)
	// recordDescCreatedAt is the schema descriptor for created_at field.
	recordDescCreatedAt := recordFields[5].Descriptor()
	// record.DefaultCreatedAt holds the default value on creation for the created_at field.
	record.DefaultCreatedAt = recordDescCreatedAt.Default.(func() time.Time)
	// recordDescUpdatedAt is the schema descriptor for updated_at field.
	recordDescUpdatedAt := recordFields[6].Descriptor()
	// record.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	record.DefaultUpdatedAt = recordDescUpdatedAt.Default.(func() time.Time)
	// recordDescID is the schema descriptor for id field.
	recordDescID := recordFields[0].Descriptor()
	// record.DefaultID holds the default value on creation for the id field.
	record.DefaultID = recordDescID.Default.(func() string)
	// record.IDValidator is a validator for the "id" field. It is called by the builders before save.
	record.IDValidator = func() func(string) error {
		validators := recordDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[2].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[1].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = func() func(string) error {
		validators := userDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
