// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"slacker/internal/biz"
	"slacker/internal/conf"
	"slacker/internal/server"
	"slacker/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(logger log.Logger, confServer *conf.Server, data *conf.Data, auth *conf.Auth) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer, logger)
	userUseCase := biz.NewUserUseCase(logger)
	userService := service.NewUserService(logger, userUseCase)
	httpServer := server.NewHTTPServer(logger, confServer, userService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
