server:
  http:
    addr: 0.0.0.0:21283
    timeout: 10s
  grpc:
    addr: 0.0.0.0:10002
    timeout: 10s
data:
  database:
    driver: postgres
    source: ""  #{replace@data.database.source}
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 1s
    write_timeout: 1s
  wx:
    id: wxfc042c932a156bec #{replace@data.wx.id}
    secret: ""  #{replace@data.wx.secret}
auth:
  secret_key: teststsetstsetsetse #{replace@dauth.secret_key}
  expires_time: 360000s
  method: "256"
